### ISSUE TITLE
Support for RISC-V LLVM

### ISSUE THREAD

**Issue by sl33k** [CTSRD-CHERI/cheribuild#110]
I was trying to to build a freestanding CHERI RISC-V toolchain.
Some targets (e.g. FreeRTOS) suggest that this is possible, but I can't seem to find the correct options to built a crosscompiling LLVM which targets CHERI RISC-V.
Do I need to compile a LLVM which supports RISC-V manually to be able to build dependent targets (such as libcxx, compiler-rt and so on)?

Thanks!

**Comment by arichardson** [comment]
If you would like to build targets such as FreeRTOS, you might want to pass the flag `--include-dependencies` that should build all the required dependencies for you.
You will definitely need the `llvm` target which builds [the CHERI Clang compiler](https://github.com/CTSRD-CHERI/llvm-project).

If `--include-dependencies` does not work for you please let me know. It's aways possible that we forget to add a dependency that happens to be built already.

**Comment by jrtc27** [comment]
Closing as for many months now we've had people both internally and externally cross-compile all manner of things using cheribuild for RISC-V. If you're still having problems please open a new issue with the specific error you're hitting and documenting what exactly you've been trying.
