### ISSUE TITLE
sqlite undeclared identifiers compilation errors  

### ISSUE THREAD

**Issue by 5A1F** [CTSRD-CHERI/cheribuild#143]
Heya, 

I am getting the following compilation errors, when trying to compile sqlite with the latest cheribuild SDK

$ python cheribuild-latest/cheribuild.py -v --include-dependencies sqlite

libtool: compile:  /home/Testadmin/cheri/output/sdk/bin/clang -target mips64c128-unknown-freebsd13-purecap -pipe --sysroot=/home/Testadmin/cheri/output/sdk/sysroot128 -B/home/Testadmin/cheri/output/sdk/bin -integrated-as -G0 -msoft-float -stdlib=libc++ -mcpu=beri -mabi=purecap -mcpu=beri -cheri=128 -cheri-cap-table-abi=pcrel -Wno-unused-command-line-argument -Wall -Werror=cheri-capability-misuse -Werror=implicit-function-declaration -Werror=format -Werror=undefined-internal -Werror=incompatible-pointer-types -Werror=mips-cheri-prototypes -Werror=cheri-bitwise-operations -Werror=pass-failed -Wno-error=cheri-capability-misuse -target mips64c128-unknown-freebsd13-purecap -pipe --sysroot=/home/Testadmin/cheri/output/sdk/sysroot128 -B/home/Testadmin/cheri/output/sdk/bin -integrated-as -G0 -msoft-float -stdlib=libc++ -mcpu=beri -mabi=purecap -mcpu=beri -cheri=128 -cheri-cap-table-abi=pcrel -Wno-unused-command-line-argument -Wall -Werror=cheri-capability-misuse -Werror=implicit-function-declaration -Werror=format -Werror=undefined-internal -Werror=incompatible-pointer-types -Werror=mips-cheri-prototypes -Werror=cheri-bitwise-operations -Werror=pass-failed -Wno-error=cheri-capability-misuse -DSQLITE_OS_UNIX=1 -I. -I/home/Testadmin/cheri/sqlite/src -I/home/Testadmin/cheri/sqlite/ext/rtree -I/home/Testadmin/cheri/sqlite/ext/icu -I/home/Testadmin/cheri/sqlite/ext/fts3 -I/home/Testadmin/cheri/sqlite/ext/async -I/home/Testadmin/cheri/sqlite/ext/session -D_HAVE_SQLITE_CONFIG_H -DBUILD_sqlite -DNDEBUG -DSQLITE_THREADSAFE=1 -DSQLITE_OMIT_LOAD_EXTENSION=1 -DSQLITE_TEMP_STORE=1 -c /home/Testadmin/cheri/sqlite/src/complete.c -o complete.o
warning: unknown warning option '-Werror=mips-cheri-prototypes'; did you mean '-Werror=cheri-prototypes'? [-Wunknown-warning-option]
warning: unknown warning option '-Werror=mips-cheri-prototypes'; did you mean '-Werror=cheri-prototypes'? [-Wunknown-warning-option]
warning: warning: unknown warning option '-Werror=mips-cheri-prototypes'; did you mean '-Werror=cheri-prototypes'? [-Wunknown-warning-option]
unknown warning option '-Werror=mips-cheri-prototypes'; did you mean '-Werror=cheri-prototypes'? [-Wunknown-warning-option]
warning: unknown warning option '-Werror=mips-cheri-prototypes'; did you mean '-Werror=cheri-prototypes'? [-Wunknown-warning-option]
warning: unknown warning option '-Werror=mips-cheri-prototypes'; did you mean '-Werror=cheri-prototypes'? [-Wunknown-warning-option]
warningwarning: unknown warning option '-Werror=mips-cheri-prototypes'; did you mean '-Werror=cheri-prototypes'? [-Wunknown-warning-option]
: unknown warning option '-Werror=mips-cheri-prototypes'; did you mean '-Werror=cheri-prototypes'? [-Wunknown-warning-option]
warning: unknown warning option '-Werror=mips-cheri-prototypes'; did you mean '-Werror=cheri-prototypes'? [-Wunknown-warning-option]
warning: unknown warning option '-Werror=mips-cheri-prototypes'; did you mean '-Werror=cheri-prototypes'? [-Wunknown-warning-option]
warningwarning: : warning: unknown warning option '-Werror=mips-cheri-prototypes'; did you mean '-Werror=cheri-prototypes'? [-Wunknown-warning-option]
unknown warning option '-Werror=mips-cheri-prototypes'; did you mean '-Werror=cheri-prototypes'? [-Wunknown-warning-option]
unknown warning option '-Werror=mips-cheri-prototypes'; did you mean '-Werror=cheri-prototypes'? [-Wunknown-warning-option]
warning: unknown warning option '-Werror=mips-cheri-prototypes'; did you mean '-Werror=cheri-prototypes'? [-Wunknown-warning-option]
warning: unknown warning option '-Werror=mips-cheri-prototypes'; did you mean '-Werror=cheri-prototypes'? [-Wunknown-warning-option]
warning: warning: unknown warning option '-Werror=mips-cheri-prototypes'; did you mean '-Werror=cheri-prototypes'? [-Wunknown-warning-option]
unknown warning option '-Werror=mips-cheri-prototypes'; did you mean '-Werror=cheri-prototypes'? [-Wunknown-warning-option]
warning: unknown warning option '-Werror=mips-cheri-prototypes'; did you mean '-Werror=cheri-prototypes'? [-Wunknown-warning-option]warning: unknown warning option '-Werror=mips-cheri-prototypes'; did you mean '-Werror=cheri-prototypes'? [-Wunknown-warning-option]

warning: unknown warning option '-Werror=mips-cheri-prototypes'; did you mean '-Werror=cheri-prototypes'? [-Wunknown-warning-option]
warning: unknown warning option '-Werror=mips-cheri-prototypes'; did you mean '-Werror=cheri-prototypes'? [-Wunknown-warning-option]
warning: unknown warning option '-Werror=mips-cheri-prototypes'; did you mean '-Werror=cheri-prototypes'? [-Wunknown-warning-option]
warning: unknown warning option '-Werror=mips-cheri-prototypes'; did you mean '-Werror=cheri-prototypes'? [-Wunknown-warning-option]
warning: unknown warning option '-Werror=mips-cheri-prototypes'; did you mean '-Werror=cheri-prototypes'? [-Wunknown-warning-option]
/home/Testadmin/cheri/sqlite/src/attach.c:39:20: error: use of undeclared identifier 'TK_ID'
    if( pExpr->op!=TK_ID ){
                   ^
/home/Testadmin/cheri/sqlite/src/alter.c:76:23: error: use of undeclared identifier 'TK_SPACE'
/home/Testadmin/cheri/sqlite/src/attach.c      } while( token==TK_SPACE );
                      ^
:42:19: error: use of undeclared identifier 'TK_STRING'
      pExpr->op = TK_STRING;
                  ^
/home/Testadmin/cheri/sqlite/src/alter.c:78:21: error: use of undeclared identifier 'TK_LP'
    } while( token!=TK_LP && token!=TK_USING );
                    ^
/home/Testadmin/cheri/sqlite/src/alter.c:78:37: error: use of undeclared identifier 'TK_USING'
    } while( token!=TK_LP && token!=TK_USING );
                                    ^
/home/Testadmin/cheri/sqlite/src/auth.c:164:18: error: use of undeclared identifier 'TK_TRIGGER'
  if( pExpr->op==TK_TRIGGER ){
                 ^
/home/Testadmin/cheri/sqlite/src/analyze.c:239:30: error: use of undeclared identifier 'OP_Clear'
        sqlite3VdbeAddOp2(v, OP_Clear, aRoot[i], iDb);
                             ^
/home/Testadmin/cheri/sqlite/src/alter.c:122:16: /home/Testadmin/cheri/sqlite/src/auth.c:189:17: error: use of undeclared identifier 'TK_NULL'
    pExpr->op = TK_NULL;
                ^
error: /home/Testadmin/cheri/sqlite/src/attach.c:344:23: error: use of undeclared identifier 'TK_STRING'
    if( pAuthArg->op==TK_STRING ){
                      ^
use of undeclared identifier 'TK_REFERENCES'
    if( token==TK_REFERENCES ){
               ^
2 warning/home/Testadmin/cheri/sqlite/src/analyze.c:247:29: error: use of undeclared identifier 'OP_OpenWrite'
s    sqlite3VdbeAddOp4Int(v, OP_OpenWrite, iStatCur+i, aRoot[i], iDb, 3);
                            ^
 and 2 errors generated.
/home/Testadmin/cheri/sqlite/src/alter.c:127:22: error: use of undeclared identifier 'TK_SPACE'
      }while( token==TK_SPACE );
                     ^
/home/Testadmin/cheri/sqlite/src/attach.c:365:26: error: use of undeclared identifier 'OP_Function0'
    sqlite3VdbeAddOp4(v, OP_Function0, 0, regArgs+3-pFunc->nArg, regArgs+3,/home/Testadmin/cheri/sqlite/src/build.c:101:30: error: use of undeclared identifier 'OP_TableLock'

    sqlite3VdbeAddOp4(pVdbe, OP_TableLock, p1, p->iTab, p->isWriteLock,
                             ^
                         ^
/home/Testadmin/cheri/sqlite/src/alter.c:129:18: error: use of undeclared identifier 'TK_ILLEGAL'
      if( token==TK_ILLEGAL ) break;
                 ^
/home/Testadmin/cheri/sqlite/src/attach.c:374:26: error: use of undeclared identifier 'OP_Expire'
/home/Testadmin/cheri/sqlite/src/build.c    sqlite3VdbeAddOp1(v, OP_Expire, (type==SQLITE_ATTACH));:151:26: error: use of undeclared identifier 'OP_Halt'
    sqlite3VdbeAddOp0(v, OP_Halt);
                         ^

                         ^
/home/Testadmin/cheri/sqlite/src/alter.c:200:22: error: use of undeclared identifier 'TK_SPACE'
      }while( token==TK_SPACE );
                     ^
/home/Testadmin/cheri/sqlite/src/alter.c:213/home/Testadmin/cheri/sqlite/src/analyze.c:964:24: error: use of undeclared identifier 'OP_Function0'
:  sqlite3VdbeAddOp4(v, OP_Function0, 0, regStat4, regOut,
                       ^
18: error: use of undeclared identifier 'TK_DOT'
      if( token==TK_DOT || token==TK_ON ){
                 ^
/home/Testadmin/cheri/sqlite/src/attach.c:527:20: error: use of undeclared identifier 'TK_VARIABLE'
    if( pExpr->op==TK_VARIABLE ){
                   ^
/home/Testadmin/cheri/sqlite/src/build.c:182:11: error: use of undeclared identifier 'OP_Transaction'
          OP_Transaction,                    /* Opcode *//home/Testadmin/cheri/sqlite/src/alter.c:213:35: error: use of undeclared identifier 'TK_ON'
      if( token==TK_DOT || token==TK_ON ){
2
          ^ warnings
 generated.
                                  ^
gmake: *** [Makefile:716: auth.lo] Error 1
/home/Testadmin/cheri/sqlite/src/attach.c:529:21: error: use of undeclared identifier 'TK_NULL'
        pExpr->op = TK_NULL;
                    ^
gmake: *** Waiting for unfinished jobs....
/home/Testadmin/cheri/sqlite/src/alter.c:216:33: error: use of undeclared identifier 'TK_WHEN'
    } while( dist!=2 || (token!=TK_WHEN && token!=TK_FOR && token!=TK_BEGIN) );
                                ^
2 warnings and 7 errors generated.
/home/Testadmin/cheri/sqlite/src/analyze.c:1034:48: error: use of undeclared identifier 'OP_OpenRead'
  sqlite3OpenTable(pParse, iTabCur, iDb, pTab, OP_OpenRead);
/home/Testadmin/cheri/sqlite/src/build.c                                               ^:
195:30: error: use of undeclared identifier 'OP_VBegin'
        sqlite3VdbeAddOp4(v, OP_VBegin, 0, 0, 0, vtab, P4_VTAB);
                             ^
/home/Testadmin/cheri/sqlite/src/alter.c:216:51: error: use of undeclared identifier 'TK_FOR'
    } while( dist!=2 || (token!=TK_WHEN && token!=TK_FOR && token!=TK_BEGIN) );
                                                  ^
/home/Testadmin/cheri/sqlite/src/alter.c:216:68: error: use of undeclared identifier 'TK_BEGIN'
    } while( dist!=2 || (token!=TK_WHEN && token!=TK_FOR && token!=TK_BEGIN) );
                                                                   ^
/home/Testadmin/cheri/sqlite/src/analyze.c:1100:26: error: use of undeclared identifier 'OP_OpenRead'
    sqlite3VdbeAddOp3(v, OP_OpenRead, iIdxCur, pIdx->tnum, iDb);
                         ^
/home/Testadmin/cheri/sqlite/src/analyze.c:1117:26: error: use of undeclared identifier 'OP_Integer'
    sqlite3VdbeAddOp2(v, OP_Integer, nCol, regStat4+1);
                         ^
/home/Testadmin/cheri/sqlite/src/analyze.c:1118:26: error: use of undeclared identifier 'OP_Integer'
    sqlite3VdbeAddOp2(v, OP_Integer, pIdx->nKeyCol, regStat4+2);
                         ^
gmake: *** [Makefile:713: attach.lo] Error 1
/home/Testadmin/cheri/sqlite/src/alter.c:347:26: error: use of undeclared identifier 'OP_DropTrigger'
    sqlite3VdbeAddOp4(v, OP_DropTrigger, iTrigDb, 0, 0, pTrig->zName, 0);
                         ^
/home/Testadmin/cheri/sqlite/src/analyze.c:1119:26: error: use of undeclared identifier 'OP_Function0'
    sqlite3VdbeAddOp4(v, OP_Function0, 0, regStat4+1, regStat4,
                         ^
/home/Testadmin/cheri/sqlite/src/build.c:702:27: error: use of undeclared identifier 'OP_OpenWrite'
  sqlite3VdbeAddOp4Int(v, OP_OpenWrite, 0, MASTER_ROOT, iDb, 5);
                          ^
/home/Testadmin/cheri/sqlite/src/alter.c:352:24: error: use of undeclared identifier 'OP_DropTable'
/home/Testadmin/cheri/sqlite/src/analyze.c:1131:39: error: use of undeclared identifier 'OP_Rewind'
    addrRewind = sqlite3VdbeAddOp1(v, OP_Rewind, iIdxCur);  sqlite3VdbeAddOp4(v, OP_DropTable, iDb, 0, 0, pTab->zName, 0);

                                      ^
                       ^
/home/Testadmin/cheri/sqlite/src/analyze.c:1133:26: error: use of undeclared identifier 'OP_Integer'
    sqlite3VdbeAddOp2(v, OP_Integer, 0, regChng);
                         ^
/home/Testadmin/cheri/sqlite/src/alter.c:489:26: error: use of undeclared identifier 'OP_VRename'
    sqlite3VdbeAddOp4(v, OP_VRename, i, 0, 0,(const char*)pVTab, P4_VTAB);
                         ^
/home/Testadmin/cheri/sqlite/src/analyze.c:1152:28: error: use of undeclared identifier 'OP_Goto'
      sqlite3VdbeAddOp0(v, OP_Goto);
                           ^
/home/Testadmin/cheri/sqlite/src/alter.c:633:34: error: use of undeclared identifier 'TK_NULL'
  if( pDflt && pDflt->pLeft->op==TK_NULL ){
                                 ^
/home/Testadmin/cheri/sqlite/src/build.c:975:28: error: use of undeclared identifier 'OP_VBegin'
      sqlite3VdbeAddOp0(v, OP_VBegin);
                           ^
/home/Testadmin/cheri/sqlite/src/analyze.c:1158:30: error: use of undeclared identifier 'OP_NotNull'
        sqlite3VdbeAddOp2(v, OP_NotNull, regPrev, endDistinctTest);
                             ^
/home/Testadmin/cheri/sqlite/src/analyze.c:1163:30: error: use of undeclared identifier 'OP_Integer'
        sqlite3VdbeAddOp2(v, OP_Integer, i, regChng);
                             ^
/home/Testadmin/cheri/sqlite/src/alter.c:704:24: error: use of undeclared identifier 'OP_ReadCookie'
  sqlite3VdbeAddOp3(v, OP_ReadCookie, iDb, r1, BTREE_FILE_FORMAT);
                       ^
/home/Testadmin/cheri/sqlite/src/build.c:985:26: error: use of undeclared identifier 'OP_ReadCookie'
    sqlite3VdbeAddOp3(v, OP_ReadCookie, iDb, reg3, BTREE_FILE_FORMAT);
                         ^
/home/Testadmin/cheri/sqlite/src/alter.c:706:24: error: use of undeclared identifier 'OP_AddImm'
  sqlite3VdbeAddOp2(v, OP_AddImm, r1, -2);
                       ^
/home/Testadmin/cheri/sqlite/src/analyze.c:1164:30: error: use of undeclared identifier 'OP_Column'
        sqlite3VdbeAddOp3(v, OP_Column, iIdxCur, i, regTemp);/home/Testadmin/cheri/sqlite/src/build.c:987
:34:                             ^
error: use of undeclared identifier 'OP_If'
    addr1 = sqlite3VdbeAddOp1(v, OP_If, reg3); VdbeCoverage(v);
                                 ^
/home/Testadmin/cheri/sqlite/src/alter.c:707:24: error: use of undeclared identifier 'OP_IfPos'
  sqlite3VdbeAddOp2(v, OP_IfPos, r1, sqlite3VdbeCurrentAddr(v)+2);
                       ^
/home/Testadmin/cheri/sqlite/src/analyze.c:1166:30: error: use of undeclared identifier 'OP_Ne'
        sqlite3VdbeAddOp4(v, OP_Ne, regTemp, 0, regPrev+i, pColl, P4_COLLSEQ);
                             ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
/home/Testadmin/cheri/sqlite/src/analyze.c:1170:28: error: use of undeclared identifier 'OP_Integer'
/home/Testadmin/cheri/sqlite/src/build.c:990:26: error: use of undeclared identifier 'OP_SetCookie'      sqlite3VdbeAddOp2(v, OP_Integer, nColTest, regChng);

                           ^
    sqlite3VdbeAddOp3(v, OP_SetCookie, iDb, BTREE_FILE_FORMAT, fileFormat);
                         ^
2 warnings and 20 errors generated.
/home/Testadmin/cheri/sqlite/src/analyze.c:1184:30: error: use of undeclared identifier 'OP_Column'
        sqlite3VdbeAddOp3(v, OP_Column, iIdxCur, i, regPrev+i);
                             ^
/home/Testadmin/cheri/sqlite/src/build.c:991:26: error: use of undeclared identifier 'OP_SetCookie'
    sqlite3VdbeAddOp3(v, OP_SetCookie, iDb, BTREE_TEXT_ENCODING, ENC(db));
                         ^
/home/Testadmin/cheri/sqlite/src/analyze.c:1216:26: error: use of undeclared identifier 'OP_Function0'
/home/Testadmin/cheri/sqlite/src/build.c:1005:28: error: use of undeclared identifier 'OP_Integer'
    sqlite3VdbeAddOp4(v, OP_Function0, 1, regStat4, regTemp,
                         ^
      sqlite3VdbeAddOp2(v, OP_Integer, 0, reg2);
                           ^
/home/Testadmin/cheri/sqlite/src/analyze.c:1219:26: error: use of undeclared identifier 'OP_Next'
    sqlite3VdbeAddOp2(v, OP_Next, iIdxCur, addrNextRow); VdbeCoverage(v);
                         ^
gmake: *** [Makefile:707: alter.lo] Error 1
2 warnings generated.
2 warnings generated.
/home/Testadmin/cheri/sqlite/src/build.c:1009:48: error: use of undeclared identifier 'OP_CreateTable'
      pParse->addrCrTab = sqlite3VdbeAddOp2(v, OP_CreateTable, iDb, reg2);
                                               ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
/home/Testadmin/cheri/sqlite/src/build.c:1012:26: error: use of undeclared identifier 'OP_NewRowid'
    sqlite3VdbeAddOp2(v, OP_NewRowid, 0, reg1);
                         ^
/home/Testadmin/cheri/sqlite/src/build.c:1013:26: error: use of undeclared identifier 'OP_Blob'
    sqlite3VdbeAddOp4(v, OP_Blob, 6, reg3, 0, nullRow, P4_STATIC);
                         ^
/home/Testadmin/cheri/sqlite/src/build.c:1014:26: error: use of undeclared identifier 'OP_Insert'
    sqlite3VdbeAddOp3(v, OP_Insert, 0, reg3, reg1);
                         ^
/home/Testadmin/cheri/sqlite/src/build.c:1016:26: error: use of undeclared identifier 'OP_Close'
    sqlite3VdbeAddOp0(v, OP_Close);
                         ^
2 warnings and 20 errors generated.
/home/Testadmin/cheri/sqlite/src/build.c:1236:14: error: use of undeclared identifier 'TK_SPAN'
      x.op = TK_SPAN;
             ^
/home/Testadmin/cheri/sqlite/src/build.c:1265:14: error: use of undeclared identifier 'TK_STRING'
  if( p->op==TK_STRING ){
             ^
/home/Testadmin/cheri/sqlite/src/build.c:1266:13: error: use of undeclared identifier 'TK_ID'
    p->op = TK_ID;
            ^
gmake: *** [Makefile:710: analyze.lo] Error 1
fatal error: too many errors emitted, stopping now [-ferror-limit=]
2 warnings generated.
2 warnings generated.
2 warnings and 20 errors generated.
gmake: *** [Makefile:731: build.lo] Error 1
2 warnings generated.
2 warnings generated.
Fatal error: Command `nice gmake all -j12` failed with non-zero exit code 2

**Comment by arichardson** [comment]
I'm afraid I can't reproduce this error. Which git revision of cheribuild and sqlite are you building?

cheribuild no longer be adds `-Werror=mips-cheri-prototypes` since the flag has been renamed to `-Werror=cheri-prototypes`. Is it possible that you have a stale build directory that still uses old compile flags?
I would try deleting the sqlite build directory or run `cheribuild.py sqlite --clean` (probably best without --include-dependencies since a clean build of LLVM and CheriBSD will take a while).

**Comment by 5A1F** [comment]
Thanks that worked :)
