### ISSUE TITLE
Make cheribsd CHERI_ options filter just warn?

### ISSUE THREAD

**Issue by nwf** [CTSRD-CHERI/cheribuild#148]
The `cheribsd` target supports specifying extra `build-options` but is somewhat finicky about those containing the string `CHERI_`:

https://github.com/CTSRD-CHERI/cheribuild/blob/9c4a46d29d78c463f3a7ef3daf75c269077789bc/pycheribuild/projects/cross/cheribsd.py#L192-L195

While a reasonable warning for non-CHERI builds, it seems odd to exclude these options from hybrid builds.  This is a minor annoyance because I want to pass `-DWITH_CHERI_CAPREVOKE` to both purecap and hybrid world builds.  I could rename the option, of course.

(Separately, the warning text is stale, I think: the command line option is `cheribsd/build-options`, not `cheribsd/make-options`?)

**Comment by arichardson** [comment]
I guess this should probably be is_hybrid_or_purecap() but that didn't exist when the code was written. Changing it to a warning also sounds reasonable.
