### ISSUE TITLE
Cheribuild asks about update despite "skip-update": "true"

### ISSUE THREAD

**Issue by trasz** [CTSRD-CHERI/cheribuild#15]
With the following in ~/.config/cheribuild.json, ./cheribuild sdk still asks for update of cheribuild itself (updating other things is disabled without questions, as expected):

% ./cheribuild.py sdk run                                                                                                                                                         Sources will be stored in /home/en322/cheri                                                                                                                                                                     Build artifacts will be stored in /home/en322/cheri/output                                                                                                                                                     
Current CheriBuild checkout can be updated:  Your branch is behind 'origin/master' by 16 commits, and can be fast-forwarded.                                                                                    Would you like to update before continuing? y/[n] (Enter to skip)

**Comment by RichardsonAlex** [comment]
Yeah this is a completely different code path and happens before the command line arguments and JSON file are parsed. I could probably move it later, but is this really a problem?

**Comment by trasz** [comment]
It's not a huge deal, as long as I remember to press Enter before I switch
to other things.  Still, would be nice if I didn't have to.

2017-06-07 14:29 GMT+01:00 Alexander Richardson <notifications@github.com>:
