### ISSUE TITLE
Build against the rootfs instead of sysroot

### ISSUE THREAD

**Issue by arichardson** [CTSRD-CHERI/cheribuild#173]
This will make it easier to deal with 3rd-party libraries without having to install them to the sysroot and the rootfs.

The separate sysroot was useful for transferring between different build machines, but CheriBSD now builds on Linux+macOS as well. We should still keep a target to build a sysroot (without /usr/bin etc.) that can be used for Jenkins+docker images.

**Comment by jrtc27** [comment]
@arichardson was fbe69e8 meant to close this?

**Comment by arichardson** [comment]
I meant to do it in one of the follow-up commits once it is proven to work.
