### ISSUE TITLE
Cheribuild error- Ubuntu 18.04

### ISSUE THREAD

**Issue by antonionehme** [CTSRD-CHERI/cheribuild#175]
Hi All,

I am facing the error below when using `cheribuild.py cheribsd-riscv64-purecap -d` . I installed all the dependencies in the readme file.

![image](https://user-images.githubusercontent.com/11300985/104008439-7886f280-5177-11eb-8f27-6b062ae2221e.png)

Any tip is greatly appreciated.

**Comment by arichardson** [comment]
Hi @antonionehme , the actual error will be further up in the output, my guess is that one or more of the bmake tests failed.
What operating system are you using?

I also see you are building as root, so my guess would be that the tests might assume a non-root user. Could you paste the full output somewhere?

**Comment by antonionehme** [comment]
Hi @arichardson;

Many thanks for your response. This is the full output of the build.
[cheri.txt](https://github.com/CTSRD-CHERI/cheribuild/files/5787817/cheri.txt)

**Comment by jrtc27** [comment]
From the log:
```diff
--- /root/cheri/cheribsd/contrib/bmake/unit-tests/objdir-writable.exp   2021-01-06 11:51:18.420000000 -0500
+++ objdir-writable.out 2021-01-06 11:52:18.544000000 -0500
@@ -1,5 +1,4 @@
-make warning: OBJDIR/roobj: Permission denied.
-/tmp
+OBJDIR/roobj
 OBJDIR/roobj
 OBJDIR/roobj
 exit status 0
Failed tests: objdir-writable
```
So yes, bmake's test suite fails because root is able to override the permissions on read-only directories. Don't build as root.

**Comment by antonionehme** [comment]
This solved the issue. Many thanks to you both @arichardson @jrtc27!
