### ISSUE TITLE
postgres target fails to do distclean in some cases

### ISSUE THREAD

**Issue by trasz** [CTSRD-CHERI/cheribuild#18]
Differently from llvm or cheribsd targets, the postgres target doesn't use separate build directories for 128 and 256 bit build.  This means that doing "./cheribuild --128 postgres" can result in previously built 256 binaries to be installed.

**Comment by RichardsonAlex** [comment]
Yeah the postgres buildsystem sucks and doesn't support out-of-source builds.
I should probably add a file to the "build" directory that contains the last build type and if it doesn't match we do a clean first
