### ISSUE TITLE
SIGTTOU if cheribuild on a compilation target is invoked twice in a shell script

### ISSUE THREAD

**Issue by nwf** [CTSRD-CHERI/cheribuild#182]
I have a cheribuild wrapping script that builds the matrix of `mrs` configurations used in revocation benchmarks; because `cheribuild` doesn't really understand building the same target over and over, this script steers the system by hand by varying `--mrs/build-directory` for each invocation.  In any case, "recently" (as in, in the past few months?), if I attempt to build more than one configuration per run of the script, the second `cheribuild` process hangs with a `SIGTTOU` in response to `TCSBRK` after reaping a child:
```
[pid 109817] wait4(109818, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 109818                                                                        
[pid 109817] ioctl(0, TCSBRK, 1)        = ? ERESTARTSYS (To be restarted if SA_RESTART is set)                                                               
[pid 109817] --- SIGTTOU {si_signo=SIGTTOU, si_code=SI_KERNEL} ---                                                                                           [pid 109817] --- stopped by SIGTTOU ---                             
```

I have applied the following hack which lets things run again, but it's clearly going against the spirit of *something* as now `gave_tty_control` is an unused parameter (and `SIGTTOU` is always suppressed during restore):
```
--- a/pycheribuild/processutils.py
+++ b/pycheribuild/processutils.py
@@ -190,7 +190,7 @@ def keep_terminal_sane(gave_tty_control=False, name=""):
     finally:
         # Can seemingly get unwanted SIGTTOU's whilst restoring so just ignore
         # them temporarily.
-        with suppress_sigttou(suppress=gave_tty_control):
+        with suppress_sigttou():
             stdin_state.restore()
             stdout_state.restore()
             stderr_state.restore()
```

I don't understand what's different the second time around relative to the first, which is further evidence that the above is quite dubious.  Better suggestions appreciated.  These particular UNIX dragons have always managed to bamboozle me. :(

**Comment by arichardson** [comment]
I know ~nothing about SIGTTOU, so I'm not sure what's going on here. `git blame` says this is not my code, so I'll defer to @jrtc27 .

**Comment by jrtc27** [comment]
Oh boy. This was probably affected by 63da029de3cd7e3e750015e5ef4366c79488a6b0, which made things less broken for _interactive_ use when called from a non-interactive shell (i.e. script), but could well have caused new issues for scripts. I hate this part of POSIX.

**Comment by jrtc27** [comment]
I wonder... does the opening of `/dev/tty` in run_and_kill_children_on_exit end up failing so `tty` is None and we don't make ourselves the terminal leader of the new process group the second time round? Do you have a canned reproducer that doesn't require invoking any niche targets (I tend to like using disk-image where possible as it's relatively quick, repeatable and can easily be made to prompt to input)?

**Comment by nwf** [comment]
Here's a canned reproducer, at least on my setup.  I suspect if one runs without a `cheribuild.json` a much smaller example suffices.  (This particular incantation does cause `cheribuild` to ask my opinion of ssh keys, while I usually run instead something like `cheribuild.py ... & wait` because I have had perhaps related issues with terminal signal routing in the past; when run in the background like that, `cheribuild` does not stop to ask questions.)

```
#!/usr/bin/zsh

: ${CHERIBUILD_CONFIG=$(dirname $0)/cheribuild.json}

S=$(jq --raw-output '."source-root"|select(type=="string")' < ${CHERIBUILD_CONFIG})
[ -d "${S}" ] || { echo "Bad source-root '${S}'"; exit 1; }

${S}/cheribuild/cheribuild.py --config-file=${CHERIBUILD_CONFIG} disk-image-mips64-purecap
${S}/cheribuild/cheribuild.py --config-file=${CHERIBUILD_CONFIG} disk-image-riscv64-purecap
```

**Comment by arichardson** [comment]
@jrtc27 @nwf Should we go ahead and commit the workaround since it seems to fix a bug lots of people are running into?

**Comment by drpdr** [comment]
> @drpdr Did it fix the issue you were seeing, or have you not yet verified it?

Sorry for the late feedback. The workaround above works as expected. No more "pledge: network" when running multiple subsequent instances.

CC @ltratt

**Comment by jacobbramley** [comment]
I see the same behaviour (with `SIGTTOU`), and can reproduce it with a trivial example (in a script):

```
./cheribuild.py rsync-morello-purecap
./cheribuild.py rsync-morello-purecap
```

The first invocation builds fine, but the second hangs as described.

@nwf's workaround fixes it for me.

**Comment by arichardson** [comment]
Just ran into the same issue trying to call cheribuild.py with "subprocess.check_call()" from another script. Hopefully https://github.com/CTSRD-CHERI/cheribuild/pull/310 fixes the issue.
