### ISSUE TITLE
Add option to build purecap and non-purecap kernels in the same build

### ISSUE THREAD

**Issue by arichardson** [CTSRD-CHERI/cheribuild#195]
The `build-fpga-kernels` option is additive, whereas the purecap-kernels option replaces the default kernel config.
We can of course run cheribuild again with `--skip-buildworld` but that seems fragile. Adding an option that builds both (with the purecap one as the default kernel) seems like the better solution.
Or alternatively change `pure-cap-kernel` to build the purecap kernel and the non-purecap one.

**Comment by arichardson** [comment]
See https://github.com/CTSRD-CHERI/cheribsd/pull/987

**Comment by jrtc27** [comment]
Also purecap FGPA kernels should be gated on _both_. Probably wants a `build-purecap-kernels` option (and no `pure-cap`, that's always bugged me so much)?

**Comment by jrtc27** [comment]
I do also think the default kernel type should be a separate (dependent) option as we will likely want to produce hybrid images with an optional purecap kernel you can choose in loader for a while until it's stable and deemed not to have too much overhead?

**Comment by arichardson** [comment]
Sounds good to me. Not sure if I'll get around to implementing it this week thought.

**Comment by qwattash** [comment]
I agree that we should have a `build-purecap-kernels` option that builds both and then also builds the FPGA purecap kernels when `build-fpga-kernels` is also given. We probably don't need to build multiple images as long as we have the option to select the default kernel, or we can select one from the run job. I'll try to have a go at it this week.

**Comment by qwattash** [comment]
See #199
