### ISSUE TITLE
Per-project options

### ISSUE THREAD

**Issue by dstolfa** [CTSRD-CHERI/cheribuild#20]
Currently there is no way to specify certain build options on a per-project basis. One of those is --skip-update, which if specified per-project would allow us to do things such as upgrade LLVM and rebuild CheriBSD using the new LLVM.

**Comment by arichardson** [comment]
Per-project skip-update was added in https://github.com/CTSRD-CHERI/cheribuild/commit/16b32f8ea048e647e83b15d0237c5f4dbd854adc
