### ISSUE TITLE
Error when building LLVM for run-riscv64-purecap (Unknown argument)

### ISSUE THREAD

**Issue by OxonTechRyan** [CTSRD-CHERI/cheribuild#200]
When running the below command on a fresh system we encounter an error during the build the build phase when the system attempts to build LLVM. We have installed all of the packages suggested in the Pre-Build Setup section.
```
python3 cheribuild.py run-riscv64-purecap -d
```
Below is the error we encounter:
```
cd /home/cheri/cheri/build/llvm-project-build && env PKG_CONFIG_PATH=/home/cheri/cheri/output/bootstrap/lib/pkgconfig:/home/cheri/cheri/output/bootstrap/libdata/pkgconfig: nice cmake --build . -j6 --target all --
Unknown argument -j6
Usage: cmake --build <dir> [options] [-- [native-options]]
Options:
  <dir>          = Project binary directory to be built.
  --target <tgt> = Build <tgt> instead of default targets.
                   May only be specified once.
  --config <cfg> = For multi-configuration tools, choose <cfg>.
  --clean-first  = Build target 'clean' first, then build.
                   (To clean only, use --target 'clean'.)
  --use-stderr   = Ignored.  Behavior is default in CMake >= 3.0.
  --             = Pass remaining options to the native tool.
Fatal error: Command `nice cmake --build . -j6 --target all --` failed with non-zero exit code 1
```
System Details:
```
Ubuntu 18.04 (All current updates)
CMake Version: 3.10.2
Ninja Version:  1.8.2
```
#### Extra Details

We have tested building with a few different commits and have determined that c0751cb is the latest commit that works and allows us to build and run successfully, so it looks like one of the commits on April 21st may be the cause of the issue. On the working commit the make command output is  ```nice ninja all -j6```. We think the issue is related to the self.run_make inside the project.py file.

If you need any extra information please let me know.

Edit:
It looks like the -j6 argument is being passed in the wrong place and should be at the end of command after -- instead on the middle, testing this by running the build manually and it works.

Fails:
```
nice cmake --build . -j6 --target all --
```
Works:
```
nice cmake --build . --target all -- -j6
```

**Comment by ChrisMOxon** [comment]
What would the fix be?  If the args list can be compared to a list of known good cmake args then push all the rest of the args after the -- that should work right?  That should work for this and also catch any future args that should be passed to compiler.

**Comment by arichardson** [comment]
@ChrisMOxon apologies for the delay, I was on holiday.

I've now updated cheribuild to suggest building CMake if it's too old:
```
Warning: Dependency for llvm-native missing: CMake version 3.13.3 is too old (need at least 3.13.4)
Would you like to install the dependency using cheribuild? y/[N] y
Building CMake (-native) ... 
``` 

Please re-open this issue if you are still seeing CMake errors.
