### ISSUE TITLE
Some versions of cmake expect the argument to `-j` to be a separate parameter.

### ISSUE THREAD

**Issue by jacobbramley** [CTSRD-CHERI/cheribuild#204]
https://github.com/CTSRD-CHERI/cheribuild/blob/3fd3b5a06aa47e391212399137dc354372d45bef/pycheribuild/projects/project.py#L1253

This fails on my Debian 10 machine (with cmake 3.13.4). It accepts `-j 42`, but not `-j42`.

**Comment by arichardson** [comment]
Apologies, I did my testing using CMake 3.20. I've now installed 3.13.4 (the minimum required to build LLVM) so that I run tests with the oldest supported version now.
