### ISSUE TITLE
Freestanding-sdk target no longer builds

### ISSUE THREAD

**Issue by Jerryxia32** [CTSRD-CHERI/cheribuild#22]
The freestanding-sdk target no longer builds on FreeBSD. Fails at the beginning with the message:
```
./cheribuild.py --cheri-128 --source-root=./src freestanding-sdk                
Configuration file /home/hx242/.config/cheribuild.json does not exist, using only command line arguments.
Sources will be stored in /usr/home/hx242/cheribuild/src
Build artifacts will be stored in /usr/home/hx242/cheribuild/src/output
cc '-DLLVM_PATH="/usr/home/hx242/cheribuild/src/output/sdk128/bin/"' -x c - -o /usr/home/hx242/cheribuild/src/output/sdk128/bin/cheridis
Fatal error: CheriBSD build directory is missing! (Tried [PosixPath('/usr/home/hx242/cheribuild/src/build/cheribsd-obj-128/mips.mips64/usr/home/hx242/cheribuild/src/cheribsd'), PosixPath('/usr/home/hx242/cheribuild/src/build/cheribsd-obj-128/mips.mips64/usr/home/hx242/cheribuild/src/cheribsd')] )
```
The workaround is to build the full sdk, but can be painful and unnecessary as CheriOS work does not use CheriBSD bits at all

**Comment by RichardsonAlex** [comment]
On the FreeBSD the default is to pull the binutils from the CheriBSD build directory, whereas on Linux it will build those targets separately.

As a workaround you can use `cheribuild.py elftoolchain llvm qemu`. And if you also need `ld.bfd` also build the `gnu-binutils` target.

**Comment by Jerryxia32** [comment]
Yes. Basically I thought freestanding meant not depending on CheriBSD and just building the compiler toolchain, and it would be nice if this is true on both platforms. In my brief testing it seems building the three you mentioned can work on both Linux and FreeBSD (at least for standalone CheriOS work), and I wonder if freestanding-sdk could just be an alias for the three. Not sure about including gnu-binutils, seems bfd is having trouble with more and more of our compiler changes than lld.
