### ISSUE TITLE
VCU118-run.py

### ISSUE THREAD

**Issue by pig-pig-yang** [CTSRD-CHERI/cheribuild#265]
I have been using VCU118 to run CheriBSD based on Toooba recently. I see that BIOS and kernel need to be configured in the script. How do I get them?

**Comment by jrtc27** [comment]
Answered on Slack:

> Both are built with cheribuild. Firmware is bbl-gfe-baremetal-riscv64-purecap, CheriBSD is cheribsd-mfs-root-kernel-riscv64-purecap with the --cheribsd-mfs-root-kernel-riscv64-purecap/build-fpga-kernels option.
