### ISSUE TITLE
Testing for compiler lld support writes a file named -

### ISSUE THREAD

**Issue by nwf** [CTSRD-CHERI/cheribuild#28]
The test in `pycheribuild/projects/project.py`'s `canUseLLd` causes (some versions of?) `clang` (at least) to generate a file named `-` in the current working directory, which, while not fatal, is unsightly.  It's not clear to me if it's worth using a temporary path, which is `unlink()`ed on succss, or if we can get away with `"/dev/null"` rather than `"-"`, since some compiler might conceivably try invoking `unlink()` before `open()`ing an existing output.  Eliminating `"-o"` entirely results in, as traditional but unfortunate, `a.out`.

**Comment by arichardson** [comment]
Ah yes I believe this is a bug in lld that doesn't treat - as stdout. I've fixed it in our fork of lld but I believe upstream still has that bug. I think /dev/null is the correct solution since we're not trying to support windows.
