### ISSUE TITLE
Need purecap emulation enviroment with a C-compiler in it ?

### ISSUE THREAD

**Issue by bsdphk** [CTSRD-CHERI/cheribuild#283]
I've been wanting to try out Varnish Cache under CHERI since Robert first told me about the idea.

To do that I need a purecap emulation environment with a C-compiler in it.

How can I build that ?

**Comment by jrtc27** [comment]
Build the llvm-riscv64-hybrid-for-purecap-rootfs or morello-llvm-morello-hybrid-for-purecap-rootfs targets as appropriate before the disk-image-foo target, though life will be much less painful if you cross-build rather than run a compiler under CHERI QEMU

**Comment by brooksdavis** [comment]
Morello image (e.g., one built and run with `cheribuild {cheribsd,disk-image,run}-morello-purecap`), run `pkg64 install llvm-base` to get a `/usr/bin/cc` that produces native binaries.

If you're running qemu on FreeBSD, you may need to use an external DNS server with something like `echo nameserver 8.8.8.8 > /etc/resolv.conf`.

**Comment by jrtc27** [comment]
Various options exist for this
