### ISSUE TITLE
qtwebkit fails to build because cheribuild thinks the CMake version is 0.0.0

### ISSUE THREAD

**Issue by kgudka** [CTSRD-CHERI/cheribuild#30]
Looks like it is due to `_get_cmake_version`:

```python
1043     def _get_cmake_version(self):
1044         if not Path(self.configureCommand).exists():
1045             return (0, 0, 0)
1046         return get_program_version(self.configureCommand, program_name=b"cmake")
```

`self.configureCommand` is set to `"cmake"` and so the if test succeeds, as it's not an absolute path. I can work around this for now by setting the `CMAKE_COMMAND` environment variable to the full path to `cmake`.

**Comment by arichardson** [comment]
Ah I changed the cmake version detection logic but forgot to update qtwebkit. Will fix
