### ISSUE TITLE
LLVM-Objdump displays <unknown> in place of morello capability instructions

### ISSUE THREAD

**Issue by jkressel** [CTSRD-CHERI/cheribuild#306]
Hi,
I'm having an issue with llvm-objdump not displaying morello capability instructions. I built the morello sdk using `./cheribuild.py cheribsd-sdk-morello-purecap -d` which completed without issue. I am then attempting to disassemble a small program using the following command: `~/cheri/output/morello-sdk/bin/llvm-objdump -d main`, which results in the output described. Below is an example of the kind of thing I'm seeing:

`  211450: 67 00 80 d2   mov     x7, #3`
  `211454: 08 01 00 90   adrp    x8, 0x231000 <main+0x134>`
  `211458: 00 0d 42 c2   <unknown>`
  `21145c: e2 0b 40 c2   <unknown>`
  `211460: 21 00 80 52   mov     w1, #1`

is there something I'm missing?

**Comment by jrtc27** [comment]
Hybrid code requires `--mattr=+morello`, only purecap code automatically disassembles Morello instructions (since there’s a flag to say a file is purecap but nothing to distinguish non-Morello and hybrid Morello in the file).
