### ISSUE TITLE
C-compiler on CherriBSD Qemu?

### ISSUE THREAD

**Issue by bond187** [CTSRD-CHERI/cheribuild#312]
Hello. I am new to CheriBSD and am running it on qemu with `./cheribuild.py --include-dependencies run-riscv64-purecap`. I'd like to compile C code within qemu with clang, but I cannot figure out how to do this. The [documentation](https://www.cl.cam.ac.uk/research/security/ctsrd/cheri/cheri-llvm.html) seems to suggest that a compiler will be built along with other dependencies, but I cannot find how to call it. Thank you!

**Comment by jrtc27** [comment]
You don't want to, it's excruciatingly slow inside CHERI QEMU. Cross-compile with ~/cheri/output/sdk/bin/clang; there's a helper wrapper in ~/cheri/output/sdk/utils/cheribsd-riscv64-purecap-clang that'll pass the right flags for cross-compiling (`-target riscv64-unknown-freebsd13 --sysroot=$HOME/cheri/output/rootfs-riscv64-purecap -B$HOME/cheri/output/sdk/bin -march=rv64imafdcxcheri -mabi=l64pc128d -mno-relax`).

If despite that warning you really really really want to, build llvm-riscv64-hybrid-for-purecap-rootfs and re-create your disk image.

**Comment by bond187** [comment]
Thanks so much for your answer. One follow up: once I've cross-compiled my program and have the binary, how do I get that binary to be included in a new qemu image?

**Comment by jrtc27** [comment]
Copy it into ~/cheri/output/rootfs-riscv64-purecap/usr/local or ...-purecap/opt (anywhere else will work until you rebuild CheriBSD itself; those directories are explicitly preserved by cheribuild as they're for third-party software) then rebuild your disk image.

**Comment by bond187** [comment]
That works! Thanks a ton for your help.

**Comment by zintown** [comment]
It works for me too. Thanks
