### ISSUE TITLE
How to use SMB mount with ./cheribuild.py -d run-riscv64-purecap

### ISSUE THREAD

**Issue by yunji-yunji** [CTSRD-CHERI/cheribuild#317]
I remember that there was a description of how to mount my directory to QEMU in the link below. But I cannot access this link anymore.
- https://www.cl.cam.ac.uk/~nwf20/cheri-exercises-book/introduction/run-qemu-release.html

When I run QEMU using the `./cheribuild.py -d run-riscv64-purecap` command in Ubuntu 22.04, how can I access the folder containing my binary files?

**Comment by yunji-yunji** [comment]
Issue #312 solved this issue.

**Comment by nwf** [comment]
#312 suggests copying it into the disk image and rebuilding.  The build of the exercises you link to above was deleted for being very stale.  You probably want to follow `cheribuild`'s instructions, which it prints out when you start QEMU; on my machine, for example, it says:
```
Providing /cheri/source/mainline over SMB to the guest. Use `mkdir -p /srcroot && mount_smbfs -I 10.0.2.4 -N //10.0.2.4/source_root /srcroot` to mount it
Providing /cheri/build/mainline over SMB to the guest. Use `mkdir -p /buildroot && mount_smbfs -I 10.0.2.4 -N //10.0.2.4/build_root /buildroot` to mount it
Providing /cheri/out/mainline over SMB to the guest. Use `mkdir -p /outputroot && mount_smbfs -I 10.0.2.4 -N //10.0.2.4/output_root /outputroot` to mount it
Providing /cheri/out/mainline/rootfs-riscv64-purecap over SMB to the guest. Use `mkdir -p /rootfs && mount_smbfs -I 10.0.2.4 -N //10.0.2.4/rootfs /rootfs` to mount it
```
