### ISSUE TITLE
CrossCompileCMakeProject missing some compiler flags

### ISSUE THREAD

**Issue by kgudka** [CTSRD-CHERI/cheribuild#32]
Due to a recent change, `CrossCompileCMakeProject` doesn't seem to pass the following compiler flags anymore:

`-mabi=purecap -mcpu=mips4 -cheri=128|256`

I noticed this with `QtWebKit`. Does `qt5.py` need to be updated or is it a bug in `CrossCompileCMakeProject`?

**Comment by arichardson** [comment]
I thought I had fixed that issue. I'll look into it
