### ISSUE TITLE
Failing freebsd and cheribsd builds on macOS. pkg-config --exists libarchive

### ISSUE THREAD

**Issue by graymalkin** [CTSRD-CHERI/cheribuild#340]
There is a bug in the ports install of libarchive on macOS which causes builds of cheribsd to fail when cheribuild.py checks the dependencies. Specifically, at `pycheribuild/projects/cross/cheribsd.py:430`. The workaround for this is documented in https://github.com/Homebrew/homebrew-core/issues/117869 .

A work-around for cheribuild if this doesn't get fixed soon is to use the `--modversion` option for pkg-config rather than the `--exists` option. I'm not certain if this workaround would break things further down. The one listed on homebrew-core should behave though.

**Comment by arichardson** [comment]
Ah I had no idea `--exists` also checked dependencies. It sounds like changing it to `--modversion` should be safe (unless there are dependencies we check for that don't define a version?).
