### ISSUE TITLE
Error in cross compilation

### ISSUE THREAD

**Issue by 1771644923** [CTSRD-CHERI/cheribuild#356]
![Snipaste_2023-03-04_12-54-27](https://user-images.githubusercontent.com/73010351/222878800-50693095-b6d8-43f2-8f91-d112d875a5da.png)

**Comment by jrtc27** [comment]
1. cheribsd-riscv64-purecap-clang is wrapper that already provides the various -target/--sysroot/-B/-march/-mabi/-mno-relax options
2. Have you built cheribsd-riscv64-purecap so that sysroot exists?

**Comment by 1771644923** [comment]
Yes, I have built cheribsd and have the sysroot directory, but this error has been reported all the time. And several of my classmates and I are all constructed in this way, and all have the same mistakes

**Comment by jrtc27** [comment]
> --sysroot=/home/cheri/output/rootfs-riscv64-purecap

If you had omitted that and let the wrapper script provide the *correct* default it would work. As it stands that's not pointing at ~/cheri, i.e. /home/gusp/cheri or $HOME/cheri; you're missing the username. Ditto with the path in -B.

You should really either be doing `~/cheri/output/sdk/utils/cheribsd-riscv64-purecap-clang print-pointer.c` or `~/cheri/output/sdk/bin/clang -target riscv64-unknown-freebsd14 --sysroot=$HOME/cheri/output/rootfs-riscv64-purecap -B$HOME/cheri/output/sdk/bin -march=rv64imafdcxcheri -mabi=l64pc128d -mno-relax`. If you really insist on it you can use the wrapper script with the explicit arguments but it serves absolutely no purpose to mix the two, the whole point of the wrapper script is that you don't have to provide all the standard arguments.

**Comment by jrtc27** [comment]
I'm also not going to ask why your print-pointer.c is in ~/cheri/output/sdk/utils...

**Comment by 1771644923** [comment]
Thanks so much for your answer. Why can't the executable file run after I compile it. 

./a.out
bash: ./a.out: Unable to execute binary file: executable file format error

**Comment by jrtc27** [comment]
Because your machine is an x86 Linux system, not a CHERI-RISC-V CheriBSD one.
