### ISSUE TITLE
About Rebuilding Images

### ISSUE THREAD

**Issue by 1771644923** [CTSRD-CHERI/cheribuild#360]
Why do I rebuild images every time. Execution
./ Cheribuild.py disk image iscv64 purecap. 
**Windows disk availability will decrease by 10G. The disks of the virtual machine have not changed.**

My operating system: windows11

Operating environment: debian10

**Comment by jrtc27** [comment]
This is not a bug report.

**Comment by 1771644923** [comment]
> This is not a bug report.

Sorry, it has just been resolved.
