### ISSUE TITLE
Make it possible to do a non-shallow git clone

### ISSUE THREAD

**Issue by khilangudka** [CTSRD-CHERI/cheribuild#40]
By default, the git clone depth is 1 but one might want the full repo history. 

Would be good to make this configurable.

EDIT:
a shallow clone can be converted to an unshallow one with this command:
`git fetch --unshallow`

**Comment by arichardson** [comment]
Yeah I think it makes sense to add a config option. If you just want to build something there is no need for the history but for editing it is extremely useful.

Should this be per-project or global?

**Comment by kgudka** [comment]
Probably global would be fine, but maybe it's fine to leave as is and then one can do `git fetch --unshallow` for those repositories for which they need the history (as mentioned in 8e3906581db6434c204a9efe4882b7fbb85e7234).
