### ISSUE TITLE
kernconfs argument in wrong format

### ISSUE THREAD

**Issue by zhugengyu** [CTSRD-CHERI/cheribuild#408]
![image](https://github.com/user-attachments/assets/5b4a6a8f-f099-47d1-b515-f5aa608e716c)

hello all, I found my kernel conf string passed in wrong format, and I fixed it like
PS: my dev environment is Ubuntu 20.04 WSL in Win11, and my target is AARCH64 Upstream FreeBSD

```py
        #kernel_options.set(KERNCONF=" ".join(kernconfs))
        kernel_options.set(KERNCONF=r"{}".format(kernconfs))
        if self.with_debug_info:
            kernel_options.set(DEBUG="-g")
        if extra_make_args:
            kernel_options.set(**extra_make_args)
        return kernel_options
```

**Comment by jrtc27** [comment]
What command did you run? kernconfs is supposed to be a list of strings, as documented by the function's type hints:

```
def kernel_make_args_for_config(self, kernconfs: "list[str]", extra_make_args) -> MakeOptions:
```

Given `phykmod-freebsd-aarch64` isn't something that exists in this repository I can only assume you've introduced that class and used the wrong type in your own code?

**Comment by zhugengyu** [comment]
yes, you are right, I get it wrong here
