### ISSUE TITLE
rm -rf cheri/output/sdk/sysroot128.delete-me-pls fails

### ISSUE THREAD

**Issue by bsdphk** [CTSRD-CHERI/cheribuild#55]
Missing a `chflags -R noschg` ?

    Warning: Previous async cleanup of  /root/cheri/output/sdk/sysroot128 failed. Cleaning up now
    Fatal error:Command `rm -rf /root/cheri/output/sdk/sysroot128.delete-me-pls` failed with non-zero exit code 1. Working directory was /cheri/cheribuild

**Comment by arichardson** [comment]
Ah yes it only does the noschg for the async clean. I'll look into it tomorrow.

**Comment by jrtc27** [comment]
Did this ever get fixed?

**Comment by arichardson** [comment]
I believe this should no longer be happening now that we make it harder to build as root.
