### ISSUE TITLE
Support for -march, -mabi and -mcmodel RISC-V command line flags

### ISSUE THREAD

**Issue by heshamelmatary** [CTSRD-CHERI/cheribuild#63]
Providing those in the command line is gonna be very useful especially when we're doing multilib

**Comment by jrtc27** [comment]
We support IMAC and IMAFDC, both with optional Xcheri, and (double) hard-float and soft-float ABIs. -mcmodel is a waste of time because everything should use medany, and it makes no difference for pure-capability code.
