### ISSUE TITLE
Automatically generate symlinks for each configuration in .conf

### ISSUE THREAD

**Issue by nicomazz** [CTSRD-CHERI/cheribuild#86]

**Comment by jrtc27** [comment]
I don't understand what this is asking for; cheribuild's config files are ~/.config/foo.json, no .conf in sight, and there is only one configuration, ~/.config/cheribuild.json. Any other configuration comes from the user either manually specifying a file or having a foo-cheribuild command that symlinks to cheribuild, so "each configuration" is either a singleton set or infinite. Thus, closing this issue; if you have a more concrete enhancement request then please file a new issue with more detail.

**Comment by arichardson** [comment]
The idea here was to add a `foo-cheribuild.py` if `~/.config/foo-cheribuild.json` exists. I use a few of these: debug-cheribuild.py implicitly loads ~/.config/debug-cheribuild.json, etc.

However, creating them automatically would mean scanning ~/.config on every startup and I'm not particularly keen on doing that.
