### ISSUE TITLE
'libarchive-dev' listed twice in prebuild instructions

### ISSUE THREAD

**Issue by anaaktge** [CTSRD-CHERI/cheribuild#90]
I noticed that 'libarchive-dev' is listed twice in the prerequisite installations (It's actually listed three time in the initial instructions I received out of band). I deleted the two duplicates when I did my install, and it appears to be fine. Is there a reason it is listed twice in the apt-get install invocation? Build is often black magic to me. :)

**Comment by arichardson** [comment]
apt will happily ignore duplicates, but that was not intended.
