### ISSUE TITLE
Q: Is there a flag to suppress warnings during initial installation?

### ISSUE THREAD

**Issue by anaaktge** [CTSRD-CHERI/cheribuild#91]
During my first run of cheribuild.py to setup & configure the world for the first time, a large number of warnings cropped up, most about disk space usage, slowing down installation. It was rather annoying. Is there an argument like the classic '-f' to suppress? 

If not, it would be very nice to have one to make on-boarding and set up smoother and add it to the getting started directions.

**Comment by arichardson** [comment]
I agree that the README could do with being updated and improved.
There is a -f/--force option that will bypass all user prompts and we should probably recommend it for the initial setup.

**Comment by arichardson** [comment]
Most of these prompts should no longer show up. The prompt for cloning was removed in 4ec807a89f3ea36eb50987a489997388ac8da0bf. I think a completely clean build should no longer result in any prompts.
