### ISSUE TITLE
cheribuild.py hangs on Ubuntu 18.04

### ISSUE THREAD

**Issue by bharadwajy** [CTSRD-CHERI/cheribuild#93]
Hello!

Can I please get some guidance on getting past the hang (no progress for the past 11 hrs) that I see while running cheribuild.py on Ubuntu.py? Thanks for any help.

Following is the output of pstree - which I hope will provide the context and commands used.

```
$ pstree -ahlAt 29358
python3 ./cheribuild.py run-purecap -d --config-file /home/bharadwaj/datadrive/github/src/CHERI/.config/cheribuild.json --source-root /home/bharadwaj/datadrive/github/src/CHERI
  `-bmake -DDB_FROM_SRC -DNO_CLEAN -DI_REALLY_MEAN_NO_CLEAN -DNO_ROOT -DBUILD_WITH_STRICT_TMPPATH TARGET mips TARGET_ARCH mips64c128 CHERI 128 TARGET_CPUTYPE cheri -DWITH_CHERI DEBUG_FLAGS -g LOCAL_XTOOL_DIRS lib/libnetbsd usr.sbin/makefs usr.bin/mkimg CHERI_USE_CAP_TABLE pcrel XAR /home/bharadwaj/datadrive/github/src/CHERI/output/sdk/bin/llvm-ar XNM /home/bharadwaj/datadrive/github/src/CHERI/output/sdk/bin/llvm-nm XSIZE /home/bharadwaj/datadrive/github/src/CHERI/output/sdk/bin/llvm-size XSTRIPBIN /home/bharadwaj/datadrive/github/src/CHERI/output/sdk/bin/llvm-strip XSTRINGS /home/bharadwaj/datadrive/github/src/CHERI/output/sdk/bin/llvm-strings XOBJCOPY /home/bharadwaj/datadrive/github/src/CHERI/output/sdk/bin/llvm-objcopy XRANLIB /home/bharadwaj/datadrive/github/src/CHERI/output/sdk/bin/llvm-ranlib RANLIBFLAGS  -DNO_SHARE METALOG /dev/null -DWITH_TESTS -DWITH_BINUTILS -DWITHOUT_CLANG -DWITHOUT_GCC -DWITHOUT_GDB -DWITHOUT_LLD -DWITHOUT_LLDB -DWITHOUT_MAN -DWITHOUT_MAIL -DWITHOUT_SENDMAIL -DWITHOUT_VT -DWITHOUT_DEBUG_FILES -DWITHOUT_BOOT -DWITH_AUTO_OBJ -DWITHOUT_GCC_BOOTSTRAP -DWITHOUT_CLANG_BOOTSTRAP -DWITHOUT_LLD_BOOTSTRAP -DWITHOUT_LIB32 -DWITHOUT_RESCUE -DWITH_ELFTOOLCHAIN_BOOTSTRAP -DWITH_TOOLCHAIN -DWITHOUT_BINUTILS_BOOTSTRAP -s -de installsysroot -j12 -DWITH_AUTO_OBJ -DNO_CLEAN -DBUILD_WITH_OPIPEFAIL
      `-sh
          `-bmake -m /mnt/datadrive/github/src/CHERI/cheribsd/share/mk -f Makefile.inc1 -DDB_FROM_SRC -DMALLOC_PRODUCTION LOCAL_DIRS ctsrd tools/tools/atsectl LOCAL_LIB_DIRS ctsrd/lib LOCAL_MTREE ctsrd/ctsrd.mtree -DWITH_CHERI128 TARGET mips TARGET_ARCH mips64c128 installsysroot
              `-sh -e
                  `-bmake -f Makefile.inc1 INSTALL install -N /mnt/datadrive/github/src/CHERI/cheribsd/etc -U -M /dev/null -D /home/bharadwaj/datadrive/github/src/CHERI/output/sdk/sysroot128 MTREE_CMD mtree -N /mnt/datadrive/github/src/CHERI/cheribsd/etc -W -DSYSROOT_ONLY MK_TESTS no __MAKE_SHELL /tmp/install.XXyp6ryB/sh -DNO_ROOT METALOG /dev/null reinstallsysroot
                      `-sh -e
                          `-bmake -f Makefile.inc1 LOCAL_MTREE ctsrd/ctsrd.mtree hierarchy
                              `-sh -e
                                  `-bmake LOCAL_MTREE ctsrd/ctsrd.mtree PATH /mnt/datadrive/github/src/CHERI/build/cheribsd-purecap-128-build/mnt/datadrive/github/src/CHERI/cheribsd/mips.mips64c128/tmp/usr/sbin:/mnt/datadrive/github/src/CHERI/build/cheribsd-purecap-128-build/mnt/datadrive/github/src/CHERI/cheribsd/mips.mips64c128/tmp/usr/bin:/mnt/datadrive/github/src/CHERI/build/cheribsd-purecap-128-build/mnt/datadrive/github/src/CHERI/cheribsd/mips.mips64c128/tmp/legacy/usr/sbin:/mnt/datadrive/github/src/CHERI/build/cheribsd-purecap-128-build/mnt/datadrive/github/src/CHERI/cheribsd/mips.mips64c128/tmp/legacy/usr/bin:/mnt/datadrive/github/src/CHERI/build/cheribsd-purecap-128-build/mnt/datadrive/github/src/CHERI/cheribsd/mips.mips64c128/tmp/legacy/bin:/mnt/datadrive/github/src/CHERI/build/cheribsd-purecap-128-build/mnt/datadrive/github/src/CHERI/cheribsd/mips.mips64c128/tmp/legacy/usr/libexec: METALOG /dev/null -DNO_ROOT distrib-dirs
                                      `-sh -e
                                          `-cat -l


$ ll /home/bharadwaj/datadrive/github/src/CHERI
total 32
drwxr-xr-x  8 bharadwaj bharadwaj 4096 May 14 22:52 ./
drwxrwxr-x  3 bharadwaj bharadwaj 4096 May 14 22:09 ../
drwxr-xr-x  5 bharadwaj bharadwaj 4096 May 14 22:54 build/
drwxr-xr-x 26 bharadwaj bharadwaj 4096 May 14 22:54 cheribsd/
drwxr-xr-x  9 bharadwaj bharadwaj 4096 May 14 22:09 cheribuild/
drwxr-xr-x 21 bharadwaj bharadwaj 4096 May 14 22:29 llvm-project/
drwxr-xr-x  4 bharadwaj bharadwaj 4096 May 14 23:12 output/
drwxr-xr-x 56 bharadwaj bharadwaj 4096 May 14 22:13 qemu/
```

**Comment by jrtc27** [comment]
That means cat is blocked trying to do a `fctl(F_SETLKW)` on the METALOG in your rootfs directory. Is your data drive formatted/mounted in a way that would stop that working? Did you kill a previous run and possibly leave that file still locked?

**Comment by jrtc27** [comment]
(specifically, `/home/bharadwaj/datadrive/github/src/CHERI/output/rootfs-purecap128/METALOG` in your case)

**Comment by jrtc27** [comment]
Ah, you're building a sysroot, so a different output directory, but the `METALOG /dev/null` also shows it's trying to lock that. You should find that `echo foo | cat -l >> /dev/null` similarly hangs. Either your `/dev/null` is broken or something else hasn't released that lock. (Yes, the lock is unnecessary in this very specific case, but it's not worth optimising for that)

**Comment by bharadwajy** [comment]
I was wondering about the `-l` option of the `cat` command. It is not honored by the `cat` command on Linux.

```
$ echo foo | cat -l >> /dev/null
cat: invalid option -- 'l'
Try 'cat --help' for more information.
$ cat -l >> ~/foo
cat: invalid option -- 'l'
Try 'cat --help' for more information.
```

Do you think it would help if I remove the `-l` option from `cat` command? If so, can you point me to the source location?

Thanks!

**Comment by jrtc27** [comment]
Correct, it's a BSDism. If you remove the `-l`, it will work for building a sysroot, but break horribly when trying to assemble a rootfs for a disk image. That is not the right answer. @arichardson is cat meant to be a bootstrap tool?

**Comment by arichardson** [comment]
@jrtc27 Yes, cat is bootstrapped from the CheriBSD tree. We could modify it to skip locking for /dev/null?

**Comment by jrtc27** [comment]
We could, but that's an upstream FreeBSD issue, and is just unnecessary serialisation. There is a more fundamental bug going on here, given this is meant to work and we have many people successfully using Linux to build CheriBSD.

**Comment by nwf** [comment]
FWIW, my `cheribuild` checkout contains

```
diff --git a/pycheribuild/projects/cross/cheribsd.py b/pycheribuild/projects/cross/cheribsd.py
index deaa811c..942d384b 100644
--- a/pycheribuild/projects/cross/cheribsd.py
+++ b/pycheribuild/projects/cross/cheribsd.py
@@ -805,7 +805,7 @@ class BuildFreeBSD(BuildFreeBSDBase):
             # By default also create a sysroot when installing world
             installsysroot_args = install_world_args.copy()
             # No need for the files in /usr/share and the METALOG file
-            installsysroot_args.set(NO_SHARE=True, METALOG="/dev/null")
+            installsysroot_args.set(NO_SHARE=True)
             installsysroot_args.set_env(DESTDIR=self.get_corresponding_sysroot())
             if sysroot_only:
                 if not self.has_installsysroot_target:
```

because I ran into something similar in the past.  Apparently the docker daemon has been known to lock `/dev/null` (e.g., https://github.com/moby/moby/issues/31182).  Hilarious.

**Comment by arichardson** [comment]
@nwf could you commit this? I only added the /dev/null to avoid creating a METALOG file in the sysroot.

**Comment by bharadwajy** [comment]
> FWIW, my `cheribuild` checkout contains
> 
> ```
> diff --git a/pycheribuild/projects/cross/cheribsd.py b/pycheribuild/projects/cross/cheribsd.py
> index deaa811c..942d384b 100644
> --- a/pycheribuild/projects/cross/cheribsd.py
> +++ b/pycheribuild/projects/cross/cheribsd.py
> @@ -805,7 +805,7 @@ class BuildFreeBSD(BuildFreeBSDBase):
>              # By default also create a sysroot when installing world
>              installsysroot_args = install_world_args.copy()
>              # No need for the files in /usr/share and the METALOG file
> -            installsysroot_args.set(NO_SHARE=True, METALOG="/dev/null")
> +            installsysroot_args.set(NO_SHARE=True)
>              installsysroot_args.set_env(DESTDIR=self.get_corresponding_sysroot())
>              if sysroot_only:
>                  if not self.has_installsysroot_target:
> ```
> 
> because I ran into something similar in the past. Apparently the docker daemon has been known to lock `/dev/null` (e.g., [moby/moby#31182](https://github.com/moby/moby/issues/31182)). Hilarious.

That change worked for me. Just providing feedback, in case you find it helpful.

Thanks to @jrtc27, @arichardson and @nwf for the quick responses. Really appreciate it.

**Comment by nwf** [comment]
@arichardson: Done.  Hopefully nobody noticed my tripping over the git UI again.  (Sigh.)
